AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda function that detects the Dominant Language in the provided input text using Amazon Comprehend.
Resources:
  DetectLanguageLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: src/
      MemorySize: 128
      Timeout: 40
      Architectures:
        - arm64
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Sid: LambdaDetectDominantLanguage
            Effect: Allow
            Action:
            - comprehend:DetectDominantLanguage
            Resource: '*'       
Outputs:
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref DetectLanguageLambdaFunction

